Repository imniladri/DevHub, pull requests merged in 2022-02, with the labels that each got.

#16 Added some good useful Android Libraries in the Android page and link…
  CONTRIBUTING.md
  client/data/android.data.js
  client/index.html
  client/src/androidpack.html
  client/src/apipack.html
  client/src/csspack.html
  client/src/iconpack.html
  client/src/imgpack.html
  client/src/jspack.html
Labels: JWOC, easy

#17 Added new feature of theme shifter that changes main color theme.
  CONTRIBUTING.md
  client/css/components/footer.css
  client/css/components/header.css
  client/css/components/settings.css
  client/css/components/theme.css
  client/css/pages/index.css
  client/index.html
  client/js/main.js
  client/src/androidpack.html
  client/src/apipack.html
  client/src/csspack.html
  client/src/iconpack.html
  client/src/imgpack.html
  client/src/jspack.html
Labels: JWOC, hard

#18 I have added API libraries to this project as per the issue #2
  client/data/api.data.js
  client/index.html
  client/src/androidpack.html
  client/src/apipack.html
  client/src/csspack.html
  client/src/iconpack.html
  client/src/imgpack.html
  client/src/jspack.html
Labels: JWOC, easy

#22 Changes made to 404.html and error.css pages
  client/404.html
  client/css/pages/error.css
Labels: JWOC, easy

#23 Suggested changes made to form
  client/css/pages/form.css
  client/new.html
Labels: JWOC, easy

#29 Made the form page responsive for both pc and mobile devices
  client/css/pages/form.css
  client/new.html
Labels: JWOC, Easy

#32 I added transitions to pages as per the issue #27
  client/css/components/settings.css
  client/css/components/transition.css
  client/index.html
  client/src/androidpack.html
  client/src/apipack.html
  client/src/csspack.html
  client/src/iconpack.html
  client/src/imgpack.html
  client/src/jspack.html
Labels: JWOC, Hard

#33 🚀 feat: Added Particles to the Loader Screen
  client/css/components/loader.css
  client/index.html
  client/js/main.js
  client/js/sketch.app.js
Labels: JWOC, Medium

#37 Add a floating back to top button
  client/css/components/settings.css
  client/css/pages/index.css
  client/index.html
  client/js/main.js
  client/src/androidpack.html
  client/src/apipack.html
  client/src/csspack.html
  client/src/iconpack.html
  client/src/imgpack.html
  client/src/jspack.html
  client/src/mlpack.html
Labels: JWOC, Medium
